server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true     
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    zipkin: http://localhost:9411 # se utiliza puerto 9411 ya que es el indicado por zipkin en la pagina oficial zipkin.io